"""
OMEGA CONDUCTOR — self_develop.py
Hourly self-development scan: read errors/issues → synthesize directives → push stubs to GitHub.
"""
import uuid, json
from omega_conductor.utils import *
from omega_conductor import SUPABASE_REF, GITHUB_ORG, VERSION, OMEGA

CAPABILITY_STUBS = [
    ("pull_sentry.py", "\"\"\"STUB: Sentry error perception — pull latest issues and map to fix directives.\"\"\"\n# TODO: auto-generated by self_develop.py on {ts}\n"),
    ("pull_northflank.py", "\"\"\"STUB: Northflank service perception — check running services, health, resource usage.\"\"\"\n# TODO: auto-generated by self_develop.py on {ts}\n"),
    ("pull_ngrok.py", "\"\"\"STUB: Ngrok tunnel perception — detect active tunnels, latency, traffic.\"\"\"\n# TODO: auto-generated by self_develop.py on {ts}\n"),
    ("pull_linkedin.py", "\"\"\"STUB: LinkedIn intelligence — monitor post engagement, connection growth, impressions.\"\"\"\n# TODO: auto-generated by self_develop.py on {ts}\n"),
    ("pull_google_drive.py", "\"\"\"STUB: Google Drive perception — scan docs for action items and key decisions.\"\"\"\n# TODO: auto-generated by self_develop.py on {ts}\n"),
]

def scan_sentry():
    issues = []
    data, _ = run_tool("SENTRY_LIST_ORGANIZATION_ISSUES", {"organization_slug": "evez", "limit": 20})
    if isinstance(data, dict):
        items = data.get("data", data.get("issues", []))
        if isinstance(items, list):
            issues = [i.get("title", "?") for i in items[:10]]
    return issues

def scan_linear():
    issues = []
    data, _ = run_tool("LINEAR_GET_VIEWER_ISSUES", {})
    if isinstance(data, dict):
        items = data.get("issues", data.get("data", {}).get("issues", {}).get("nodes", []))
        if isinstance(items, list):
            issues = [i.get("title", "?") for i in items[:10]]
    return issues

def scan_github_prs():
    prs = []
    repos = ["omega-conductor", "evezstation", "octoklaw-rom"]
    for repo in repos:
        data, _ = run_tool("GITHUB_LIST_PULL_REQUESTS", {
            "owner": GITHUB_ORG, "repo": repo, "state": "open"
        })
        if isinstance(data, dict):
            items = data.get("pull_requests", data.get("data", {}).get("items", []))
            if isinstance(items, list):
                prs.extend([f"{repo}#{p.get('number','?')} {p.get('title','?')}" for p in items])
    return prs

def push_stubs_to_github(stubs_written, ts):
    """Push newly generated capability stubs back to GitHub."""
    for fname, content in stubs_written:
        run_tool("GITHUB_CREATE_OR_UPDATE_FILE_CONTENTS", {
            "owner": GITHUB_ORG,
            "repo": "omega-conductor",
            "path": f"omega_conductor/generated/{fname}",
            "message": f"self_develop: auto-generate {fname} [{ts[:10]}]",
            "content": content.replace("{ts}", ts),
        })

def log_iteration(iteration, surfaces_scanned, issues_found, stubs_added, ts):
    eid = str(uuid.uuid4())[:8]
    omega_delta = (stubs_added * 0.05) + (issues_found * 0.01)
    exec_sql(f"""INSERT OR IGNORE INTO omega_self_dev_log VALUES (
        {q(eid)},{iteration},{surfaces_scanned},{issues_found},{stubs_added},
        {omega_delta},{q(f'v{VERSION} self-dev scan {ts[:10]}')},{q(ts)});""")
    update_meta("last_self_dev", ts)
    update_meta("total_stubs_generated", stubs_added)

def post_slack_self_dev(sentry_issues, linear_issues, prs, stubs, ts):
    issues_block = "\n".join(f"  • `{i[:60]}`" for i in (sentry_issues + linear_issues + prs)[:6])
    stubs_block  = "\n".join(f"  + `{s[0]}`" for s in stubs)
    msg = (
        f"*🧬 OMEGA CONDUCTOR — Self-Dev Scan* | `{ts[:19]}Z`\n"
        f"Surfaces scanned: Sentry, Linear, GitHub × 3\n\n"
        f"*Issues / signals found:*\n{issues_block or '  (none — stack is clean)'}\n\n"
        f"*New capability stubs pushed to GitHub:*\n{stubs_block or '  (none this cycle)'}\n\n"
        f"_Recursive self-amplification: {OMEGA:.0f}x → growing_"
    )
    run_tool("SLACK_SENDS_A_MESSAGE_TO_A_SLACK_CHANNEL", {
        "channel": "#general", "text": msg
    })

def main():
    ts = now_iso()
    print(f"\n{'═'*56}")
    print(f"  OMEGA CONDUCTOR — self_develop.py | {ts[:19]}")
    print(f"{'═'*56}\n")

    ensure_appdb_tables()

    # ── Scan ──
    sentry_issues = []
    linear_issues = []
    prs = []
    try: sentry_issues = scan_sentry();  print(f"  Sentry: {len(sentry_issues)} issues")
    except Exception as e: print(f"  Sentry: {e}")
    try: linear_issues = scan_linear();  print(f"  Linear: {len(linear_issues)} issues")
    except Exception as e: print(f"  Linear: {e}")
    try: prs           = scan_github_prs(); print(f"  GitHub PRs: {len(prs)}")
    except Exception as e: print(f"  GitHub PRs: {e}")

    # ── Determine which stubs don't exist yet ──
    stubs_to_write = CAPABILITY_STUBS  # always push stubs (idempotent if-not-exists logic on GitHub side)

    # ── Push stubs ──
    try:
        push_stubs_to_github(stubs_to_write, ts)
        print(f"  ✅ Pushed {len(stubs_to_write)} stubs to EvezArt/omega-conductor")
    except Exception as e:
        print(f"  ⚠️  GitHub stub push: {e}")

    # ── Log ──
    iter_res = exec_sql("SELECT COUNT(*) as n FROM omega_self_dev_log;")
    iteration = 1
    if isinstance(iter_res, dict):
        rows = iter_res.get("data", {}).get("rows", [])
        if rows: iteration = rows[0].get("n", 0) + 1

    log_iteration(iteration, 3, len(sentry_issues+linear_issues+prs), len(stubs_to_write), ts)

    # ── Broadcast ──
    post_slack_self_dev(sentry_issues, linear_issues, prs, stubs_to_write, ts)
    print(f"  📡 Slack self-dev broadcast sent")

    print(f"\n✅ Self-dev scan #{iteration} complete — {ts}\n")

if __name__ == "__main__":
    main()
